autocv:
  build: .
  ports:
   - "8080:8080"
  environment:
    MONGO_PORT: 27017
  links:
   - mongo
mongo:
  image: dhermanns/rpi-mongo
  ports:
   - "27017:27017"
  #volumes:
  # - $HOME/.mongo:/data/db

